### ISSUE TITLE
Dynamic query in Invenio_search

### ISSUE THREAD

**Issue by PSvishnu93** [inveniosoftware/invenio-search#143] opened 2018-06-20 09:51 UTC
I want to write a dynamic query. The query to be written is completely dependent on the get request. Is there any way to write a dynamic query and process that query to get results from elastic search

**Comment by lnielsen** [comment] 2018-06-20 11:56
Closing as duplicate of inveniosoftware/invenio-records-rest#216

**Closed by lnielsen** 2018-06-20 11:56 UTC
